development:
  adapter: postgresql
  encoding: unicode
  database: deals
  pool: 5
  username: wal33d
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: deals_db
  pool: 5
  username: wal33d
  password: