development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: deals
  pool: 5
  username: aquataze
  password: WaleedHG91!

production:
  adapter: postgresql
  encoding: unicode
  database: deals_db
  pool: 5
  username: wal33d
  password:
