development:
  adapter: postgresql
  encoding: unicode
  database: deals
  host: localhost
  pool: 5
  username: aquataze
  password: WaleedHG91!

production:
  adapter: postgresql
  encoding: unicode
  database: deals
  host: localhost
  pool: 5
  username: aquataze
  password:
