Admin.create!(:name => "Wal33d",
             :email => "aquataze@yahoo.com", 
                 :password =>"testpass", 
                 :created_at => 2.days.ago,
             :last_sign_in_at => 1.day.ago,
             :updated_at => 5.hours.ago)
Admin.create!(:name => "Bill",
             :email => "dealsunlimitedinc@gmail.com", 
                 :password =>"testpass", 
                 :created_at => 2.days.ago,
             :last_sign_in_at => 1.day.ago,
             :updated_at => 5.hours.ago)
Admin.create!(:name => "Hussein",
             :email => "dealsunlimited@live.com", 
                 :password =>"testpass", 
                 :created_at => 2.days.ago,
             :last_sign_in_at => 1.day.ago,
             :updated_at => 5.hours.ago)
require 'csv'      
CSV.foreach('db/cars.csv', :headers => true, :encoding => 'windows-1251:utf-8') do |row|
  Vehicle.create!(row.to_hash)
end
CSV.foreach('db/trucks.csv', :headers => true, :encoding => 'windows-1251:utf-8') do |row|
  Vehicle.create!(row.to_hash)
end
CSV.foreach('db/suvs.csv', :headers => true, :encoding => 'windows-1251:utf-8') do |row|
  Vehicle.create!(row.to_hash)
end

AutoMake.create!([
  {code: "Any", title: ""},
  {code: "ACURA", title: "Acura"},
  {code: "ALFA", title: "Alfa Romeo"},
  {code: "AMC", title: "AMC"},
  {code: "ASTON", title: "Aston Martin"},
  {code: "AUDI", title: "Audi"},
  {code: "AVANTI", title: "Avanti"},
  {code: "BENTL", title: "Bentley"},
  {code: "BMW", title: "BMW"},
  {code: "BUICK", title: "Buick"},
  {code: "CAD", title: "Cadillac"},
  {code: "CHEV", title: "Chevrolet"},
  {code: "CHRY", title: "Chrysler"},
  {code: "DAEW", title: "Daewoo"},
  {code: "DAIHAT", title: "Daihatsu"},
  {code: "DATSUN", title: "Datsun"},
  {code: "DELOREAN", title: "DeLorean"},
  {code: "DODGE", title: "Dodge"},
  {code: "EAGLE", title: "Eagle"},
  {code: "FER", title: "Ferrari"},
  {code: "FIAT", title: "FIAT"},
  {code: "FISK", title: "Fisker"},
  {code: "FORD", title: "Ford"},
  {code: "FREIGHT", title: "Freightliner"},
  {code: "GEO", title: "Geo"},
  {code: "GMC", title: "GMC"},
  {code: "HONDA", title: "Honda"},
  {code: "AMGEN", title: "HUMMER"},
  {code: "HYUND", title: "Hyundai"},
  {code: "INFIN", title: "Infiniti"},
  {code: "ISU", title: "Isuzu"},
  {code: "JAG", title: "Jaguar"},
  {code: "JEEP", title: "Jeep"},
  {code: "KIA", title: "Kia"},
  {code: "LAM", title: "Lamborghini"},
  {code: "LAN", title: "Lancia"},
  {code: "ROV", title: "Land Rover"},
  {code: "LEXUS", title: "Lexus"},
  {code: "LINC", title: "Lincoln"},
  {code: "LOTUS", title: "Lotus"},
  {code: "MAS", title: "Maserati"},
  {code: "MAYBACH", title: "Maybach"},
  {code: "MAZDA", title: "Mazda"},
  {code: "MCLAREN", title: "McLaren"},
  {code: "MB", title: "Mercedes-Benz"},
  {code: "MERC", title: "Mercury"},
  {code: "MERKUR", title: "Merkur"},
  {code: "MINI", title: "MINI"},
  {code: "MIT", title: "Mitsubishi"},
  {code: "NISSAN", title: "Nissan"},
  {code: "OLDS", title: "Oldsmobile"},
  {code: "PEUG", title: "Peugeot"},
  {code: "PLYM", title: "Plymouth"},
  {code: "PONT", title: "Pontiac"},
  {code: "POR", title: "Porsche"},
  {code: "RAM", title: "RAM"},
  {code: "REN", title: "Renault"},
  {code: "RR", title: "Rolls-Royce"},
  {code: "SAAB", title: "Saab"},
  {code: "SATURN", title: "Saturn"},
  {code: "SCION", title: "Scion"},
  {code: "SMART", title: "smart"},
  {code: "SRT", title: "SRT"},
  {code: "STERL", title: "Sterling"},
  {code: "SUB", title: "Subaru"},
  {code: "SUZUKI", title: "Suzuki"},
  {code: "TESLA", title: "Tesla"},
  {code: "TOYOTA", title: "Toyota"},
  {code: "TRI", title: "Triumph"},
  {code: "VOLKS", title: "Volkswagen"},
  {code: "VOLVO", title: "Volvo"},
  {code: "YUGO", title: "Yu go"}
])
AutoModel.create!([
  {code: "Any", title: "", auto_make_id: 1},

  {code: "CL_MODELS", title: "CL ", auto_make_id: 1},
  {code: "2.2CL", title: "2.2CL", auto_make_id: 1},
  {code: "2.3CL", title: "2.3CL", auto_make_id: 1},
  {code: "3.0CL", title: "3.0CL", auto_make_id: 1},
  {code: "3.2CL", title: "3.2CL", auto_make_id: 1},
  {code: "ILX", title: "ILX", auto_make_id: 1},
  {code: "INTEG", title: "Integra", auto_make_id: 1},
  {code: "LEGEND", title: "Legend", auto_make_id: 1},
  {code: "MDX", title: "MDX", auto_make_id: 1},
  {code: "NSX", title: "NSX", auto_make_id: 1},
  {code: "RDX", title: "RDX", auto_make_id: 1},
  {code: "RL_MODELS", title: "RL ", auto_make_id: 1},
  {code: "3.5RL", title: "3.5 RL", auto_make_id: 1},
  {code: "RL", title: "RL", auto_make_id: 1},
  {code: "RSX", title: "RSX", auto_make_id: 1},
  {code: "SLX", title: "SLX", auto_make_id: 1},
  {code: "TL_MODELS", title: "TL ", auto_make_id: 1},
  {code: "2.5TL", title: "2.5TL", auto_make_id: 1},
  {code: "3.2TL", title: "3.2TL", auto_make_id: 1},
  {code: "TL", title: "TL", auto_make_id: 1},
  {code: "TSX", title: "TSX", auto_make_id: 1},
  {code: "VIGOR", title: "Vigor", auto_make_id: 1},
  {code: "ZDX", title: "ZDX", auto_make_id: 1},
  {code: "ACUOTH", title: "Acura", auto_make_id: 1},
  {code: "ALFA164", title: "164", auto_make_id: 2},
  {code: "ALFA8C", title: "8C Competizione", auto_make_id: 2},
  {code: "ALFAGT", title: "GTV-6", auto_make_id: 2},
  {code: "MIL", title: "Milano", auto_make_id: 2},
  {code: "SP:id", title: "Sp:ider", auto_make_id: 2},
  {code: "ALFAOTH", title: "Alfa Romeo", auto_make_id: 2},
  {code: "AMCALLIAN", title: "Alliance", auto_make_id: 3},
  {code: "CON", title: "Concord", auto_make_id: 3},
  {code: "EAGLE", title: "Eagle", auto_make_id: 3},
  {code: "AMCENC", title: "Encore", auto_make_id: 3},
  {code: "AMCSPIRIT", title: "Spirit", auto_make_id: 3},
  {code: "AMCOTH", title: "AMC", auto_make_id: 3},
  {code: "DB7", title: "DB7", auto_make_id: 4},
  {code: "DB9", title: "DB9", auto_make_id: 4},
  {code: "DBS", title: "DBS", auto_make_id: 4},
  {code: "LAGONDA", title: "Lagonda", auto_make_id: 4},
  {code: "RAP:idE", title: "Rap:ide", auto_make_id: 4},
  {code: "V12VANT", title: "V12 Vantage", auto_make_id: 4},
  {code: "VANTAGE", title: "V8 Vantage", auto_make_id: 4},
  {code: "VANQUISH", title: "Vanquish", auto_make_id: 4},
  {code: "VIRAGE", title: "Virage", auto_make_id: 4},
  {code: "UNAVAILAST", title: "Aston Martin", auto_make_id: 4},
  {code: "AUDI100", title: "100", auto_make_id: 5},
  {code: "AUDI200", title: "200", auto_make_id: 5},
  {code: "4000", title: "4000", auto_make_id: 5},
  {code: "5000", title: "5000", auto_make_id: 5},
  {code: "80", title: "80", auto_make_id: 5},
  {code: "90", title: "90", auto_make_id: 5},
  {code: "A3", title: "A3", auto_make_id: 5},
  {code: "A4", title: "A4", auto_make_id: 5},
  {code: "A5", title: "A5", auto_make_id: 5},
  {code: "A6", title: "A6", auto_make_id: 5},
  {code: "A7", title: "A7", auto_make_id: 5},
  {code: "A8", title: "A8", auto_make_id: 5},
  {code: "ALLRDQUA", title: "allroad", auto_make_id: 5},
  {code: "AUDICABRI", title: "Cabriolet", auto_make_id: 5},
  {code: "AUDICOUPE", title: "Coupe", auto_make_id: 5},
  {code: "Q3", title: "Q3", auto_make_id: 5},
  {code: "Q5", title: "Q5", auto_make_id: 5},
  {code: "Q7", title: "Q7", auto_make_id: 5},
  {code: "QUATTR", title: "Quattro", auto_make_id: 5},
  {code: "R8", title: "R8", auto_make_id: 5},
  {code: "RS4", title: "RS 4", auto_make_id: 5},
  {code: "RS5", title: "RS 5", auto_make_id: 5},
  {code: "RS6", title: "RS 6", auto_make_id: 5},
  {code: "S4", title: "S4", auto_make_id: 5},
  {code: "S5", title: "S5", auto_make_id: 5},
  {code: "S6", title: "S6", auto_make_id: 5},
  {code: "S7", title: "S7", auto_make_id: 5},
  {code: "S8", title: "S8", auto_make_id: 5},
  {code: "TT", title: "TT", auto_make_id: 5},
  {code: "TTRS", title: "TT RS", auto_make_id: 5},
  {code: "TTS", title: "TTS", auto_make_id: 5},
  {code: "V8", title: "V8 Quattro", auto_make_id: 5},
  {code: "AUDOTH", title: "Audi", auto_make_id: 5},
  {code: "CONVERT", title: "Convertible", auto_make_id: 6},
  {code: "COUPEAVANT", title: "Coupe", auto_make_id: 6},
  {code: "SEDAN", title: "Sedan", auto_make_id: 6},
  {code: "UNAVAILAVA", title: "Avanti", auto_make_id: 6},
  {code: "ARNAGE", title: "Arnage", auto_make_id: 7},
  {code: "AZURE", title: "Azure", auto_make_id: 7},
  {code: "BROOKLANDS", title: "Brooklands", auto_make_id: 7},
  {code: "BENCONT", title: "Continental", auto_make_id: 7},
  {code: "CORNICHE", title: "Corniche", auto_make_id: 7},
  {code: "BENEIGHT", title: "Eight", auto_make_id: 7},
  {code: "BENMUL", title: "Mulsanne", auto_make_id: 7},
  {code: "BENTURBO", title: "Turbo R", auto_make_id: 7},
  {code: "UNAVAILBEN", title: "Bentley", auto_make_id: 7},
  {code: "1_SERIES", title: "1 Series ", auto_make_id: 8},
  {code: "128I", title: "128i", auto_make_id: 8},
  {code: "135I", title: "135i", auto_make_id: 8},
  {code: "135IS", title: "135is", auto_make_id: 8},
  {code: "3_SERIES", title: "3 Series ", auto_make_id: 8},
  {code: "318I", title: "318i", auto_make_id: 8},
  {code: "318IC", title: "318iC", auto_make_id: 8},
  {code: "318IS", title: "318iS", auto_make_id: 8},
  {code: "318TI", title: "318ti", auto_make_id: 8},
  {code: "320I", title: "320i", auto_make_id: 8},
  {code: "323CI", title: "323ci", auto_make_id: 8},
  {code: "323I", title: "323i", auto_make_id: 8},
  {code: "323IS", title: "323is", auto_make_id: 8},
  {code: "323IT", title: "323iT", auto_make_id: 8},
  {code: "325CI", title: "325Ci", auto_make_id: 8},
  {code: "325E", title: "325e", auto_make_id: 8},
  {code: "325ES", title: "325es", auto_make_id: 8},
  {code: "325I", title: "325i", auto_make_id: 8},
  {code: "325IS", title: "325is", auto_make_id: 8},
  {code: "325IX", title: "325iX", auto_make_id: 8},
  {code: "325XI", title: "325xi", auto_make_id: 8},
  {code: "328CI", title: "328Ci", auto_make_id: 8},
  {code: "328I", title: "328i", auto_make_id: 8},
  {code: "328IS", title: "328iS", auto_make_id: 8},
  {code: "328XI", title: "328xi", auto_make_id: 8},
  {code: "330CI", title: "330Ci", auto_make_id: 8},
  {code: "330I", title: "330i", auto_make_id: 8},
  {code: "330XI", title: "330xi", auto_make_id: 8},
  {code: "335D", title: "335d", auto_make_id: 8},
  {code: "335I", title: "335i", auto_make_id: 8},
  {code: "335IS", title: "335is", auto_make_id: 8},
  {code: "335XI", title: "335xi", auto_make_id: 8},
  {code: "ACTIVE3", title: "ActiveHybr:id 3", auto_make_id: 8},
  {code: "BMW325", title: "325", auto_make_id: 8},
  {code: "5_SERIES", title: "5 Series ", auto_make_id: 8},
  {code: "524TD", title: "524td", auto_make_id: 8},
  {code: "525I", title: "525i", auto_make_id: 8},
  {code: "525XI", title: "525xi", auto_make_id: 8},
  {code: "528E", title: "528e", auto_make_id: 8},
  {code: "528I", title: "528i", auto_make_id: 8},
  {code: "528IT", title: "528iT", auto_make_id: 8},
  {code: "528XI", title: "528xi", auto_make_id: 8},
  {code: "530I", title: "530i", auto_make_id: 8},
  {code: "530IT", title: "530iT", auto_make_id: 8},
  {code: "530XI", title: "530xi", auto_make_id: 8},
  {code: "533I", title: "533i", auto_make_id: 8},
  {code: "535I", title: "535i", auto_make_id: 8},
  {code: "535IGT", title: "535i Gran Turismo", auto_make_id: 8},
  {code: "535XI", title: "535xi", auto_make_id: 8},
  {code: "540I", title: "540i", auto_make_id: 8},
  {code: "545I", title: "545i", auto_make_id: 8},
  {code: "550I", title: "550i", auto_make_id: 8},
  {code: "550IGT", title: "550i Gran Turismo", auto_make_id: 8},
  {code: "ACTIVE5", title: "ActiveHybr:id 5", auto_make_id: 8},
  {code: "6_SERIES", title: "6 Series ", auto_make_id: 8},
  {code: "633CSI", title: "633CSi", auto_make_id: 8},
  {code: "635CSI", title: "635CSi", auto_make_id: 8},
  {code: "640I", title: "640i", auto_make_id: 8},
  {code: "640IGC", title: "640i Gran Coupe", auto_make_id: 8},
  {code: "645CI", title: "645Ci", auto_make_id: 8},
  {code: "650I", title: "650i", auto_make_id: 8},
  {code: "650IGC", title: "650i Gran Coupe", auto_make_id: 8},
  {code: "L6", title: "L6", auto_make_id: 8},
  {code: "7_SERIES", title: "7 Series ", auto_make_id: 8},
  {code: "733I", title: "733i", auto_make_id: 8},
  {code: "735I", title: "735i", auto_make_id: 8},
  {code: "735IL", title: "735iL", auto_make_id: 8},
  {code: "740I", title: "740i", auto_make_id: 8},
  {code: "740IL", title: "740iL", auto_make_id: 8},
  {code: "740LI", title: "740Li", auto_make_id: 8},
  {code: "745I", title: "745i", auto_make_id: 8},
  {code: "745LI", title: "745Li", auto_make_id: 8},
  {code: "750I", title: "750i", auto_make_id: 8},
  {code: "750IL", title: "750iL", auto_make_id: 8},
  {code: "750LI", title: "750Li", auto_make_id: 8},
  {code: "760I", title: "760i", auto_make_id: 8},
  {code: "760LI", title: "760Li", auto_make_id: 8},
  {code: "ACTIVE7", title: "ActiveHybr:id 7", auto_make_id: 8},
  {code: "ALPINAB7", title: "Alpina B7", auto_make_id: 8},
  {code: "8_SERIES", title: "8 Series ", auto_make_id: 8},
  {code: "840CI", title: "840Ci", auto_make_id: 8},
  {code: "850CI", title: "850Ci", auto_make_id: 8},
  {code: "850CSI", title: "850CSi", auto_make_id: 8},
  {code: "850I", title: "850i", auto_make_id: 8},
  {code: "L_SERIES", title: "L Series ", auto_make_id: 8},
  {code: "L7", title: "L7", auto_make_id: 8},
  {code: "M_SERIES", title: "M Series ", auto_make_id: 8},
  {code: "1SERIESM", title: "1 Series M", auto_make_id: 8},
  {code: "BMWMCOUPE", title: "M Coupe", auto_make_id: 8},
  {code: "BMWROAD", title: "M Roadster", auto_make_id: 8},
  {code: "M3", title: "M3", auto_make_id: 8},
  {code: "M5", title: "M5", auto_make_id: 8},
  {code: "M6", title: "M6", auto_make_id: 8},
  {code: "X5M", title: "X5 M", auto_make_id: 8},
  {code: "X6M", title: "X6 M", auto_make_id: 8},
  {code: "X_SERIES", title: "X Series ", auto_make_id: 8},
  {code: "ACTIVEX6", title: "ActiveHybr:id X6", auto_make_id: 8},
  {code: "X1", title: "X1", auto_make_id: 8},
  {code: "X3", title: "X3", auto_make_id: 8},
  {code: "X5", title: "X5", auto_make_id: 8},
  {code: "X6", title: "X6", auto_make_id: 8},
  {code: "Z_SERIES", title: "Z Series ", auto_make_id: 8},
  {code: "Z3", title: "Z3", auto_make_id: 8},
  {code: "Z4", title: "Z4", auto_make_id: 8},
  {code: "Z8", title: "Z8", auto_make_id: 8},
  {code: "BMWOTH", title: "BMW", auto_make_id: 8},
  {code: "CENT", title: "Century", auto_make_id: 9},
  {code: "ELEC", title: "Electra", auto_make_id: 9},
  {code: "ENCLAVE", title: "Enclave", auto_make_id: 9},
  {code: "BUIENC", title: "Encore", auto_make_id: 9},
  {code: "LACROSSE", title: "LaCrosse", auto_make_id: 9},
  {code: "LESA", title: "Le Sabre", auto_make_id: 9},
  {code: "LUCERNE", title: "Lucerne", auto_make_id: 9},
  {code: "PARK", title: "Park Avenue", auto_make_id: 9},
  {code: "RAINIER", title: "Rainier", auto_make_id: 9},
  {code: "REATTA", title: "Reatta", auto_make_id: 9},
  {code: "REG", title: "Regal", auto_make_id: 9},
  {code: "RENDEZVOUS", title: "Rendezvous", auto_make_id: 9},
  {code: "RIV", title: "Riviera", auto_make_id: 9},
  {code: "BUICKROAD", title: "Roadmaster", auto_make_id: 9},
  {code: "SKYH", title: "Skyhawk", auto_make_id: 9},
  {code: "SKYL", title: "Skylark", auto_make_id: 9},
  {code: "SOMER", title: "Somerset", auto_make_id: 9},
  {code: "TERRAZA", title: "Terraza", auto_make_id: 9},
  {code: "BUVERANO", title: "Verano", auto_make_id: 9},
  {code: "BUOTH", title: "Buick", auto_make_id: 9},
  {code: "ALLANT", title: "Allante", auto_make_id: 10},
  {code: "ATS", title: "ATS", auto_make_id: 10},
  {code: "BROUGH", title: "Brougham", auto_make_id: 10},
  {code: "CATERA", title: "Catera", auto_make_id: 10},
  {code: "CIMA", title: "Cimarron", auto_make_id: 10},
  {code: "CTS", title: "CTS", auto_make_id: 10},
  {code: "DEV", title: "De Ville", auto_make_id: 10},
  {code: "DTS", title: "DTS", auto_make_id: 10},
  {code: "ELDO", title: "Eldorado", auto_make_id: 10},
  {code: "ESCALA", title: "Escalade", auto_make_id: 10},
  {code: "ESCALAESV", title: "Escalade ESV", auto_make_id: 10},
  {code: "EXT", title: "Escalade EXT", auto_make_id: 10},
  {code: "FLEE", title: "Fleetwood", auto_make_id: 10},
  {code: "SEV", title: "Seville", auto_make_id: 10},
  {code: "SRX", title: "SRX", auto_make_id: 10},
  {code: "STS", title: "STS", auto_make_id: 10},
  {code: "XLR", title: "XLR", auto_make_id: 10},
  {code: "XTS", title: "XTS", auto_make_id: 10},
  {code: "CADOTH", title: "Cadillac", auto_make_id: 10},
  {code: "ASTRO", title: "Astro", auto_make_id: 11},
  {code: "AVALNCH", title: "Avalanche", auto_make_id: 11},
  {code: "AVEO", title: "Aveo", auto_make_id: 11},
  {code: "AVEO5", title: "Aveo5", auto_make_id: 11},
  {code: "BERETT", title: "Beretta", auto_make_id: 11},
  {code: "BLAZER", title: "Blazer", auto_make_id: 11},
  {code: "CAM", title: "Camaro", auto_make_id: 11},
  {code: "CAP", title: "Caprice", auto_make_id: 11},
  {code: "CHECAPS", title: "Captiva Sport", auto_make_id: 11},
  {code: "CAV", title: "Cavalier", auto_make_id: 11},
  {code: "CELE", title: "Celebrity", auto_make_id: 11},
  {code: "CHEVETTE", title: "Chevette", auto_make_id: 11},
  {code: "CITATION", title: "Citation", auto_make_id: 11},
  {code: "COBALT", title: "Cobalt", auto_make_id: 11},
  {code: "COLORADO", title: "Colorado", auto_make_id: 11},
  {code: "CORSI", title: "Corsica", auto_make_id: 11},
  {code: "CORV", title: "Corvette", auto_make_id: 11},
  {code: "CRUZE", title: "Cruze", auto_make_id: 11},
  {code: "ELCAM", title: "El Camino", auto_make_id: 11},
  {code: "EQUINOX", title: "Equinox", auto_make_id: 11},
  {code: "G15EXP", title: "Express Van", auto_make_id: 11},
  {code: "G10", title: "G Van", auto_make_id: 11},
  {code: "HHR", title: "HHR", auto_make_id: 11},
  {code: "CHEVIMP", title: "Impala", auto_make_id: 11},
  {code: "KODC4500", title: "Kodiak C4500", auto_make_id: 11},
  {code: "LUMINA", title: "Lumina", auto_make_id: 11},
  {code: "LAPV", title: "Lumina APV", auto_make_id: 11},
  {code: "LUV", title: "LUV", auto_make_id: 11},
  {code: "MALI", title: "Malibu", auto_make_id: 11},
  {code: "CHVMETR", title: "Metro", auto_make_id: 11},
  {code: "CHEVMONT", title: "Monte Carlo", auto_make_id: 11},
  {code: "NOVA", title: "Nova", auto_make_id: 11},
  {code: "CHEVPRIZM", title: "Prizm", auto_make_id: 11},
  {code: "CHVST", title: "S10 Blazer", auto_make_id: 11},
  {code: "S10PICKUP", title: "S10 Pickup", auto_make_id: 11},
  {code: "CHEV150", title: "Silverado and C/K1500", auto_make_id: 11},
  {code: "CHEVC25", title: "Silverado and C/K2500", auto_make_id: 11},
  {code: "CH3500PU", title: "Silverado and C/K3500", auto_make_id: 11},
  {code: "SONIC", title: "Sonic", auto_make_id: 11},
  {code: "SPARK", title: "Spark", auto_make_id: 11},
  {code: "CHEVSPEC", title: "Spectrum", auto_make_id: 11},
  {code: "CHSPRINT", title: "Sprint", auto_make_id: 11},
  {code: "SSR", title: "SSR", auto_make_id: 11},
  {code: "CHEVSUB", title: "Suburban", auto_make_id: 11},
  {code: "TAHOE", title: "Tahoe", auto_make_id: 11},
  {code: "TRACKE", title: "Tracker", auto_make_id: 11},
  {code: "TRAILBLZ", title: "TrailBlazer", auto_make_id: 11},
  {code: "TRAILBZEXT", title: "TrailBlazer EXT", auto_make_id: 11},
  {code: "TRAVERSE", title: "Traverse", auto_make_id: 11},
  {code: "UPLANDER", title: "Uplander", auto_make_id: 11},
  {code: "VENTUR", title: "Venture", auto_make_id: 11},
  {code: "VOLT", title: "Volt", auto_make_id: 11},
  {code: "CHEOTH", title: "Chevrolet", auto_make_id: 11},
  {code: "CHRYS200", title: "200", auto_make_id: 12},
  {code: "300", title: "300", auto_make_id: 12},
  {code: "CHRY300", title: "300M", auto_make_id: 12},
  {code: "ASPEN", title: "Aspen", auto_make_id: 12},
  {code: "CARAVAN", title: "Caravan", auto_make_id: 12},
  {code: "CIRRUS", title: "Cirrus", auto_make_id: 12},
  {code: "CONC", title: "Concorde", auto_make_id: 12},
  {code: "CHRYCONQ", title: "Conquest", auto_make_id: 12},
  {code: "CORDOBA", title: "Cordoba", auto_make_id: 12},
  {code: "CROSSFIRE", title: "Crossfire", auto_make_id: 12},
  {code: "ECLASS", title: "E Class", auto_make_id: 12},
  {code: "FIFTH", title: "Fifth Avenue", auto_make_id: 12},
  {code: "CHRYGRANDV", title: "Grand Voyager", auto_make_id: 12},
  {code: "IMPE", title: "Imperial", auto_make_id: 12},
  {code: "INTREP:id", title: "Intrep:id", auto_make_id: 12},
  {code: "CHRYLAS", title: "Laser", auto_make_id: 12},
  {code: "LEBA", title: "LeBaron", auto_make_id: 12},
  {code: "LHS", title: "LHS", auto_make_id: 12},
  {code: "CHRYNEON", title: "Neon", auto_make_id: 12},
  {code: "NY", title: "New Yorker", auto_make_id: 12},
  {code: "NEWPORT", title: "Newport", auto_make_id: 12},
  {code: "PACIFICA", title: "Pacifica", auto_make_id: 12},
  {code: "CHPROWLE", title: "Prowler", auto_make_id: 12},
  {code: "PTCRUIS", title: "PT Cruiser", auto_make_id: 12},
  {code: "CHRYSEB", title: "Sebring", auto_make_id: 12},
  {code: "CHRYTC", title: "TC by Maserati", auto_make_id: 12},
  {code: "TANDC", title: "Town & Country", auto_make_id: 12},
  {code: "VOYAGER", title: "Voyager", auto_make_id: 12},
  {code: "CHOTH", title: "Chrysler", auto_make_id: 12},
  {code: "LANOS", title: "Lanos", auto_make_id: 13},
  {code: "LEGANZA", title: "Leganza", auto_make_id: 13},
  {code: "NUBIRA", title: "Nubira", auto_make_id: 13},
  {code: "DAEOTH", title: "Daewoo", auto_make_id: 13},
  {code: "CHAR", title: "Charade", auto_make_id: 14},
  {code: "ROCKY", title: "Rocky", auto_make_id: 14},
  {code: "DAIHOTH", title: "Daihatsu", auto_make_id: 14},
  {code: "DAT200SX", title: "200SX", auto_make_id: 15},
  {code: "DAT210", title: "210", auto_make_id: 15},
  {code: "280Z", title: "280ZX", auto_make_id: 15},
  {code: "300ZX", title: "300ZX", auto_make_id: 15},
  {code: "310", title: "310", auto_make_id: 15},
  {code: "510", title: "510", auto_make_id: 15},
  {code: "720", title: "720", auto_make_id: 15},
  {code: "810", title: "810", auto_make_id: 15},
  {code: "DATMAX", title: "Maxima", auto_make_id: 15},
  {code: "DATPU", title: "Pickup", auto_make_id: 15},
  {code: "PUL", title: "Pulsar", auto_make_id: 15},
  {code: "DATSENT", title: "Sentra", auto_make_id: 15},
  {code: "STAN", title: "Stanza", auto_make_id: 15},
  {code: "DATOTH", title: "Datsun", auto_make_id: 15},
  {code: "DMC12", title: "DMC-12", auto_make_id: 16},
  {code: "400", title: "400", auto_make_id: 17},
  {code: "DOD600", title: "600", auto_make_id: 17},
  {code: "ARI", title: "Aries", auto_make_id: 17},
  {code: "AVENGR", title: "Avenger", auto_make_id: 17},
  {code: "CALIBER", title: "Caliber", auto_make_id: 17},
  {code: "DODCARA", title: "Caravan", auto_make_id: 17},
  {code: "CHALLENGER", title: "Challenger", auto_make_id: 17},
  {code: "DODCHAR", title: "Charger", auto_make_id: 17},
  {code: "DODCOLT", title: "Colt", auto_make_id: 17},
  {code: "DODCONQ", title: "Conquest", auto_make_id: 17},
  {code: "DODDW", title: "D/W Truck", auto_make_id: 17},
  {code: "DAKOTA", title: "Dakota", auto_make_id: 17},
  {code: "DODDART", title: "Dart", auto_make_id: 17},
  {code: "DAY", title: "Daytona", auto_make_id: 17},
  {code: "DIPLOMA", title: "Diplomat", auto_make_id: 17},
  {code: "DURANG", title: "Durango", auto_make_id: 17},
  {code: "DODDYNA", title: "Dynasty", auto_make_id: 17},
  {code: "GRANDCARAV", title: "Grand Caravan", auto_make_id: 17},
  {code: "INTRE", title: "Intrep:id", auto_make_id: 17},
  {code: "JOURNEY", title: "Journey", auto_make_id: 17},
  {code: "LANCERDODG", title: "Lancer", auto_make_id: 17},
  {code: "MAGNUM", title: "Magnum", auto_make_id: 17},
  {code: "MIRADA", title: "Mirada", auto_make_id: 17},
  {code: "MONACO", title: "Monaco", auto_make_id: 17},
  {code: "DODNEON", title: "Neon", auto_make_id: 17},
  {code: "NITRO", title: "Nitro", auto_make_id: 17},
  {code: "OMNI", title: "Omni", auto_make_id: 17},
  {code: "RA:idER", title: "Ra:ider", auto_make_id: 17},
  {code: "RAM1504WD", title: "Ram 1500 Truck", auto_make_id: 17},
  {code: "RAM25002WD", title: "Ram 2500 Truck", auto_make_id: 17},
  {code: "RAM3502WD", title: "Ram 3500 Truck", auto_make_id: 17},
  {code: "RAM4500", title: "Ram 4500 Truck", auto_make_id: 17},
  {code: "DODD50", title: "Ram 50 Truck", auto_make_id: 17},
  {code: "CV", title: "RAM C/V", auto_make_id: 17},
  {code: "RAMSRT10", title: "Ram SRT-10", auto_make_id: 17},
  {code: "RAMVANV8", title: "Ram Van", auto_make_id: 17},
  {code: "RAMWAGON", title: "Ram Wagon", auto_make_id: 17},
  {code: "RAMCGR", title: "Ramcharger", auto_make_id: 17},
  {code: "RAMPAGE", title: "Rampage", auto_make_id: 17},
  {code: "DODSHAD", title: "Shadow", auto_make_id: 17},
  {code: "DODSPIR", title: "Spirit", auto_make_id: 17},
  {code: "SPRINTER", title: "Sprinter", auto_make_id: 17},
  {code: "SRT4", title: "SRT-4", auto_make_id: 17},
  {code: "STREGIS", title: "St. Regis", auto_make_id: 17},
  {code: "STEAL", title: "Stealth", auto_make_id: 17},
  {code: "STRATU", title: "Stratus", auto_make_id: 17},
  {code: "VIPER", title: "Viper", auto_make_id: 17},
  {code: "DOOTH", title: "Dodge", auto_make_id: 17},
  {code: "EAGLEMED", title: "Medallion", auto_make_id: 18},
  {code: "EAGLEPREM", title: "Premier", auto_make_id: 18},
  {code: "SUMMIT", title: "Summit", auto_make_id: 18},
  {code: "TALON", title: "Talon", auto_make_id: 18},
  {code: "VISION", title: "Vision", auto_make_id: 18},
  {code: "EAGOTH", title: "Eagle", auto_make_id: 18},
  {code: "308GTB", title: "308 GTB Quattrovalvole", auto_make_id: 19},
  {code: "308TBI", title: "308 GTBI", auto_make_id: 19},
  {code: "308GTS", title: "308 GTS Quattrovalvole", auto_make_id: 19},
  {code: "308TSI", title: "308 GTSI", auto_make_id: 19},
  {code: "328GTB", title: "328 GTB", auto_make_id: 19},
  {code: "328GTS", title: "328 GTS", auto_make_id: 19},
  {code: "348GTB", title: "348 GTB", auto_make_id: 19},
  {code: "348GTS", title: "348 GTS", auto_make_id: 19},
  {code: "348SPI", title: "348 Sp:ider", auto_make_id: 19},
  {code: "348TB", title: "348 TB", auto_make_id: 19},
  {code: "348TS", title: "348 TS", auto_make_id: 19},
  {code: "360", title: "360", auto_make_id: 19},
  {code: "456GT", title: "456 GT", auto_make_id: 19},
  {code: "456MGT", title: "456M GT", auto_make_id: 19},
  {code: "458ITALIA", title: "458 Italia", auto_make_id: 19},
  {code: "512BBI", title: "512 BBi", auto_make_id: 19},
  {code: "512M", title: "512M", auto_make_id: 19},
  {code: "512TR", title: "512TR", auto_make_id: 19},
  {code: "550M", title: "550 Maranello", auto_make_id: 19},
  {code: "575M", title: "575M Maranello", auto_make_id: 19},
  {code: "599GTB", title: "599 GTB Fiorano", auto_make_id: 19},
  {code: "599GTO", title: "599 GTO", auto_make_id: 19},
  {code: "612SCAGLIE", title: "612 Scaglietti", auto_make_id: 19},
  {code: "FERCALIF", title: "California", auto_make_id: 19},
  {code: "ENZO", title: "Enzo", auto_make_id: 19},
  {code: "F355", title: "F355", auto_make_id: 19},
  {code: "F40", title: "F40", auto_make_id: 19},
  {code: "F430", title: "F430", auto_make_id: 19},
  {code: "F50", title: "F50", auto_make_id: 19},
  {code: "FERFF", title: "FF", auto_make_id: 19},
  {code: "MOND", title: "Mondial", auto_make_id: 19},
  {code: "TEST", title: "Testarossa", auto_make_id: 19},
  {code: "UNAVAILFER", title: "Ferrari", auto_make_id: 19},
  {code: "2000", title: "2000 Sp:ider", auto_make_id: 20},
  {code: "FIAT500", title: "500", auto_make_id: 20},
  {code: "BERTON", title: "Bertone X1/9", auto_make_id: 20},
  {code: "BRAVA", title: "Brava", auto_make_id: 20},
  {code: "PININ", title: "Pininfarina Sp:ider", auto_make_id: 20},
  {code: "STRADA", title: "Strada", auto_make_id: 20},
  {code: "FIATX19", title: "X1/9", auto_make_id: 20},
  {code: "UNAVAILFIA", title: "Fiat", auto_make_id: 20},
  {code: "KARMA", title: "Karma", auto_make_id: 21},
  {code: "AERO", title: "Aerostar", auto_make_id: 22},
  {code: "ASPIRE", title: "Aspire", auto_make_id: 22},
  {code: "BRON", title: "Bronco", auto_make_id: 22},
  {code: "B2", title: "Bronco II", auto_make_id: 22},
  {code: "FOCMAX", title: "C-MAX", auto_make_id: 22},
  {code: "FORDCLUB", title: "Club Wagon", auto_make_id: 22},
  {code: "CONTOUR", title: "Contour", auto_make_id: 22},
  {code: "COURIER", title: "Courier", auto_make_id: 22},
  {code: "CROWNVIC", title: "Crown Victoria", auto_make_id: 22},
  {code: "E150ECON", title: "E-150 and Econoline 150", auto_make_id: 22},
  {code: "E250ECON", title: "E-250 and Econoline 250", auto_make_id: 22},
  {code: "E350ECON", title: "E-350 and Econoline 350", auto_make_id: 22},
  {code: "EDGE", title: "Edge", auto_make_id: 22},
  {code: "ESCAPE", title: "Escape", auto_make_id: 22},
  {code: "ESCO", title: "Escort", auto_make_id: 22},
  {code: "EXCURSION", title: "Excursion", auto_make_id: 22},
  {code: "EXP", title: "EXP", auto_make_id: 22},
  {code: "EXPEDI", title: "Expedition", auto_make_id: 22},
  {code: "EXPEDIEL", title: "Expedition EL", auto_make_id: 22},
  {code: "EXPLOR", title: "Explorer", auto_make_id: 22},
  {code: "SPORTTRAC", title: "Explorer Sport Trac", auto_make_id: 22},
  {code: "F100", title: "F100", auto_make_id: 22},
  {code: "F150PICKUP", title: "F150", auto_make_id: 22},
  {code: "F250", title: "F250", auto_make_id: 22},
  {code: "F350", title: "F350", auto_make_id: 22},
  {code: "F450", title: "F450", auto_make_id: 22},
  {code: "FAIRM", title: "Fairmont", auto_make_id: 22},
  {code: "FESTIV", title: "Festiva", auto_make_id: 22},
  {code: "FIESTA", title: "Fiesta", auto_make_id: 22},
  {code: "FIVEHUNDRE", title: "Five Hundred", auto_make_id: 22},
  {code: "FLEX", title: "Flex", auto_make_id: 22},
  {code: "FOCUS", title: "Focus", auto_make_id: 22},
  {code: "FREESTAR", title: "Freestar", auto_make_id: 22},
  {code: "FREESTYLE", title: "Freestyle", auto_make_id: 22},
  {code: "FUSION", title: "Fusion", auto_make_id: 22},
  {code: "GRANADA", title: "Granada", auto_make_id: 22},
  {code: "GT", title: "GT", auto_make_id: 22},
  {code: "LTD", title: "LTD", auto_make_id: 22},
  {code: "MUST", title: "Mustang", auto_make_id: 22},
  {code: "PROBE", title: "Probe", auto_make_id: 22},
  {code: "RANGER", title: "Ranger", auto_make_id: 22},
  {code: "TAURUS", title: "Taurus", auto_make_id: 22},
  {code: "TAURUSX", title: "Taurus X", auto_make_id: 22},
  {code: "TEMPO", title: "Tempo", auto_make_id: 22},
  {code: "TBIRD", title: "Thunderbird", auto_make_id: 22},
  {code: "TRANSCONN", title: "Transit Connect", auto_make_id: 22},
  {code: "WINDST", title: "Windstar", auto_make_id: 22},
  {code: "FORDZX2", title: "ZX2 Escort", auto_make_id: 22},
  {code: "FOOTH", title: "Ford", auto_make_id: 22},
  {code: "FRESPRINT", title: "Sprinter", auto_make_id: 23},
  {code: "GEOMETRO", title: "Metro", auto_make_id: 24},
  {code: "GEOPRIZM", title: "Prizm", auto_make_id: 24},
  {code: "SPECT", title: "Spectrum", auto_make_id: 24},
  {code: "STORM", title: "Storm", auto_make_id: 24},
  {code: "GEOTRACK", title: "Tracker", auto_make_id: 24},
  {code: "GEOOTH", title: "Geo", auto_make_id: 24},
  {code: "ACADIA", title: "Acadia", auto_make_id: 25},
  {code: "CABALLERO", title: "Caballero", auto_make_id: 25},
  {code: "CANYON", title: "Canyon", auto_make_id: 25},
  {code: "ENVOY", title: "Envoy", auto_make_id: 25},
  {code: "ENVOYXL", title: "Envoy XL", auto_make_id: 25},
  {code: "ENVOYXUV", title: "Envoy XUV", auto_make_id: 25},
  {code: "JIM", title: "Jimmy", auto_make_id: 25},
  {code: "RALLYWAG", title: "Rally Wagon", auto_make_id: 25},
  {code: "GMCS15", title: "S15 Jimmy", auto_make_id: 25},
  {code: "S15", title: "S15 Pickup", auto_make_id: 25},
  {code: "SAFARIGMC", title: "Safari", auto_make_id: 25},
  {code: "GMCSAVANA", title: "Savana", auto_make_id: 25},
  {code: "15SIPU4WD", title: "Sierra C/K1500", auto_make_id: 25},
  {code: "GMCC25PU", title: "Sierra C/K2500", auto_make_id: 25},
  {code: "GMC3500PU", title: "Sierra C/K3500", auto_make_id: 25},
  {code: "SONOMA", title: "Sonoma", auto_make_id: 25},
  {code: "SUB", title: "Suburban", auto_make_id: 25},
  {code: "GMCSYCLON", title: "Syclone", auto_make_id: 25},
  {code: "TERRAIN", title: "Terrain", auto_make_id: 25},
  {code: "TOPC4500", title: "TopKick C4500", auto_make_id: 25},
  {code: "TYPH", title: "Typhoon", auto_make_id: 25},
  {code: "GMCVANDUR", title: "Vandura", auto_make_id: 25},
  {code: "YUKON", title: "Yukon", auto_make_id: 25},
  {code: "YUKONXL", title: "Yukon XL", auto_make_id: 25},
  {code: "GMCOTH", title: "GMC", auto_make_id: 25},
  {code: "ACCORD", title: "Accord", auto_make_id: 26},
  {code: "CIVIC", title: "Civic", auto_make_id: 26},
  {code: "CRV", title: "CR-V", auto_make_id: 26},
  {code: "CRZ", title: "CR-Z", auto_make_id: 26},
  {code: "CRX", title: "CRX", auto_make_id: 26},
  {code: "CROSSTOUR_MODELS", title: "Crosstour and Accord Crosstour :auto_make_id =>  ", auto_make_id: 26},
  {code: "CROSSTOUR", title: "Accord Crosstour", auto_make_id: 26},
  {code: "HONCROSS", title: "Crosstour", auto_make_id: 26},
  {code: "HONDELSOL", title: "Del Sol", auto_make_id: 26},
  {code: "ELEMENT", title: "Element", auto_make_id: 26},
  {code: "FIT", title: "Fit", auto_make_id: 26},
  {code: "INSIGHT", title: "Insight", auto_make_id: 26},
  {code: "ODYSSEY", title: "Odyssey", auto_make_id: 26},
  {code: "PASSPO", title: "Passport", auto_make_id: 26},
  {code: "PILOT", title: "Pilot", auto_make_id: 26},
  {code: "PRE", title: "Prelude", auto_make_id: 26},
  {code: "R:idGELINE", title: "R:idgeline", auto_make_id: 26},
  {code: "S2000", title: "S2000", auto_make_id: 26},
  {code: "HONOTH", title: "Honda", auto_make_id: 26},
  {code: "HUMMER", title: "H1", auto_make_id: 27},
  {code: "H2", title: "H2", auto_make_id: 27},
  {code: "H3", title: "H3", auto_make_id: 27},
  {code: "H3T", title: "H3T", auto_make_id: 27},
  {code: "AMGOTH", title: "Hummer", auto_make_id: 27},
  {code: "ACCENT", title: "Accent", auto_make_id: 28},
  {code: "AZERA", title: "Azera", auto_make_id: 28},
  {code: "ELANTR", title: "Elantra", auto_make_id: 28},
  {code: "HYUELANCPE", title: "Elantra Coupe", auto_make_id: 28},
  {code: "ELANTOUR", title: "Elantra Touring", auto_make_id: 28},
  {code: "ENTOURAGE", title: "Entourage", auto_make_id: 28},
  {code: "EQUUS", title: "Equus", auto_make_id: 28},
  {code: "HYUEXCEL", title: "Excel", auto_make_id: 28},
  {code: "GENESIS", title: "Genesis", auto_make_id: 28},
  {code: "GENESISCPE", title: "Genesis Coupe", auto_make_id: 28},
  {code: "SANTAFE", title: "Santa Fe", auto_make_id: 28},
  {code: "SCOUPE", title: "Scoupe", auto_make_id: 28},
  {code: "SONATA", title: "Sonata", auto_make_id: 28},
  {code: "TIBURO", title: "Tiburon", auto_make_id: 28},
  {code: "TUCSON", title: "Tucson", auto_make_id: 28},
  {code: "VELOSTER", title: "Veloster", auto_make_id: 28},
  {code: "VERACRUZ", title: "Veracruz", auto_make_id: 28},
  {code: "XG300", title: "XG300", auto_make_id: 28},
  {code: "XG350", title: "XG350", auto_make_id: 28},
  {code: "HYUOTH", title: "Hyundai", auto_make_id: 28},
  {code: "EX_MODELS", title: "EX ", auto_make_id: 29},
  {code: "EX35", title: "EX35", auto_make_id: 29},
  {code: "EX37", title: "EX37", auto_make_id: 29},
  {code: "FX_MODELS", title: "FX ", auto_make_id: 29},
  {code: "FX35", title: "FX35", auto_make_id: 29},
  {code: "FX37", title: "FX37", auto_make_id: 29},
  {code: "FX45", title: "FX45", auto_make_id: 29},
  {code: "FX50", title: "FX50", auto_make_id: 29},
  {code: "G_MODELS", title: "G ", auto_make_id: 29},
  {code: "G20", title: "G20", auto_make_id: 29},
  {code: "G25", title: "G25", auto_make_id: 29},
  {code: "G35", title: "G35", auto_make_id: 29},
  {code: "G37", title: "G37", auto_make_id: 29},
  {code: "I_MODELS", title: "I ", auto_make_id: 29},
  {code: "I30", title: "I30", auto_make_id: 29},
  {code: "I35", title: "I35", auto_make_id: 29},
  {code: "J_MODELS", title: "J ", auto_make_id: 29},
  {code: "J30", title: "J30", auto_make_id: 29},
  {code: "JX_MODELS", title: "JX ", auto_make_id: 29},
  {code: "JX35", title: "JX35", auto_make_id: 29},
  {code: "M_MODELS", title: "M ", auto_make_id: 29},
  {code: "M30", title: "M30", auto_make_id: 29},
  {code: "M35", title: "M35", auto_make_id: 29},
  {code: "M35HYBR:id", title: "M35h", auto_make_id: 29},
  {code: "M37", title: "M37", auto_make_id: 29},
  {code: "M45", title: "M45", auto_make_id: 29},
  {code: "M56", title: "M56", auto_make_id: 29},
  {code: "Q_MODELS", title: "Q ", auto_make_id: 29},
  {code: "Q45", title: "Q45", auto_make_id: 29},
  {code: "QX_MODELS", title: "QX ", auto_make_id: 29},
  {code: "QX4", title: "QX4", auto_make_id: 29},
  {code: "QX56", title: "QX56", auto_make_id: 29},
  {code: "INFOTH", title: "Infiniti", auto_make_id: 29},
  {code: "AMIGO", title: "Amigo", auto_make_id: 30},
  {code: "ASCENDER", title: "Ascender", auto_make_id: 30},
  {code: "AXIOM", title: "Axiom", auto_make_id: 30},
  {code: "HOMBRE", title: "Hombre", auto_make_id: 30},
  {code: "I280", title: "i-280", auto_make_id: 30},
  {code: "I290", title: "i-290", auto_make_id: 30},
  {code: "I350", title: "i-350", auto_make_id: 30},
  {code: "I370", title: "i-370", auto_make_id: 30},
  {code: "ISUMARK", title: "I-Mark", auto_make_id: 30},
  {code: "ISUIMP", title: "Impulse", auto_make_id: 30},
  {code: "OASIS", title: "Oasis", auto_make_id: 30},
  {code: "ISUPU", title: "Pickup", auto_make_id: 30},
  {code: "RODEO", title: "Rodeo", auto_make_id: 30},
  {code: "STYLUS", title: "Stylus", auto_make_id: 30},
  {code: "TROOP", title: "Trooper", auto_make_id: 30},
  {code: "TRP2", title: "Trooper II", auto_make_id: 30},
  {code: "VEHICROSS", title: "VehiCROSS", auto_make_id: 30},
  {code: "ISUOTH", title: "Isuzu", auto_make_id: 30},
  {code: "STYPE", title: "S-Type", auto_make_id: 31},
  {code: "XTYPE", title: "X-Type", auto_make_id: 31},
  {code: "XF", title: "XF", auto_make_id: 31},
  {code: "XJ_SERIES", title: "XJ Series ", auto_make_id: 31},
  {code: "JAGXJ12", title: "XJ12", auto_make_id: 31},
  {code: "JAGXJ6", title: "XJ6", auto_make_id: 31},
  {code: "JAGXJR", title: "XJR", auto_make_id: 31},
  {code: "JAGXJRS", title: "XJR-S", auto_make_id: 31},
  {code: "JAGXJS", title: "XJS", auto_make_id: 31},
  {code: "VANDEN", title: "XJ Vanden Plas", auto_make_id: 31},
  {code: "XJ", title: "XJ", auto_make_id: 31},
  {code: "XJ8", title: "XJ8", auto_make_id: 31},
  {code: "XJ8L", title: "XJ8 L", auto_make_id: 31},
  {code: "XJSPORT", title: "XJ Sport", auto_make_id: 31},
  {code: "XK_SERIES", title: "XK Series ", auto_make_id: 31},
  {code: "JAGXK8", title: "XK8", auto_make_id: 31},
  {code: "XK", title: "XK", auto_make_id: 31},
  {code: "XKR", title: "XKR", auto_make_id: 31},
  {code: "JAGOTH", title: "Jaguar", auto_make_id: 31},
  {code: "CHER", title: "Cherokee", auto_make_id: 32},
  {code: "JEEPCJ", title: "CJ", auto_make_id: 32},
  {code: "COMANC", title: "Comanche", auto_make_id: 32},
  {code: "COMMANDER", title: "Commander", auto_make_id: 32},
  {code: "COMPASS", title: "Compass", auto_make_id: 32},
  {code: "JEEPGRAND", title: "Grand Cherokee", auto_make_id: 32},
  {code: "GRWAG", title: "Grand Wagoneer", auto_make_id: 32},
  {code: "LIBERTY", title: "Liberty", auto_make_id: 32},
  {code: "PATRIOT", title: "Patriot", auto_make_id: 32},
  {code: "JEEPPU", title: "Pickup", auto_make_id: 32},
  {code: "SCRAMBLE", title: "Scrambler", auto_make_id: 32},
  {code: "WAGONE", title: "Wagoneer", auto_make_id: 32},
  {code: "WRANGLER", title: "Wrangler", auto_make_id: 32},
  {code: "JEOTH", title: "Jeep", auto_make_id: 32},
  {code: "AMANTI", title: "Amanti", auto_make_id: 33},
  {code: "BORREGO", title: "Borrego", auto_make_id: 33},
  {code: "FORTE", title: "Forte", auto_make_id: 33},
  {code: "FORTEKOUP", title: "Forte Koup", auto_make_id: 33},
  {code: "OPTIMA", title: "Optima", auto_make_id: 33},
  {code: "RIO", title: "Rio", auto_make_id: 33},
  {code: "RIO5", title: "Rio5", auto_make_id: 33},
  {code: "RONDO", title: "Rondo", auto_make_id: 33},
  {code: "SEDONA", title: "Sedona", auto_make_id: 33},
  {code: "SEPHIA", title: "Sephia", auto_make_id: 33},
  {code: "SORENTO", title: "Sorento", auto_make_id: 33},
  {code: "SOUL", title: "Soul", auto_make_id: 33},
  {code: "SPECTRA", title: "Spectra", auto_make_id: 33},
  {code: "SPECTRA5", title: "Spectra5", auto_make_id: 33},
  {code: "SPORTA", title: "Sportage", auto_make_id: 33},
  {code: "KIAOTH", title: "Kia", auto_make_id: 33},
  {code: "AVENT", title: "Aventador", auto_make_id: 34},
  {code: "COUNT", title: "Countach", auto_make_id: 34},
  {code: "DIABLO", title: "Diablo", auto_make_id: 34},
  {code: "GALLARDO", title: "Gallardo", auto_make_id: 34},
  {code: "JALPA", title: "Jalpa", auto_make_id: 34},
  {code: "LM002", title: "LM002", auto_make_id: 34},
  {code: "MURCIELAGO", title: "Murcielago", auto_make_id: 34},
  {code: "UNAVAILLAM", title: "Lamborghini", auto_make_id: 34},
  {code: "BETA", title: "Beta", auto_make_id: 35},
  {code: "ZAGATO", title: "Zagato", auto_make_id: 35},
  {code: "UNAVAILLAN", title: "Lancia", auto_make_id: 35},
  {code: "DEFEND", title: "Defender", auto_make_id: 36},
  {code: "DISCOV", title: "Discovery", auto_make_id: 36},
  {code: "FRELNDR", title: "Freelander", auto_make_id: 36},
  {code: "LR2", title: "LR2", auto_make_id: 36},
  {code: "LR3", title: "LR3", auto_make_id: 36},
  {code: "LR4", title: "LR4", auto_make_id: 36},
  {code: "RANGE", title: "Range Rover", auto_make_id: 36},
  {code: "EVOQUE", title: "Range Rover Evoque", auto_make_id: 36},
  {code: "RANGESPORT", title: "Range Rover Sport", auto_make_id: 36},
  {code: "ROVOTH", title: "Land Rover", auto_make_id: 36},
  {code: "CT_MODELS", title: "CT ", auto_make_id: 37},
  {code: "CT200H", title: "CT 200h", auto_make_id: 37},
  {code: "ES_MODELS", title: "ES ", auto_make_id: 37},
  {code: "ES250", title: "ES 250", auto_make_id: 37},
  {code: "ES300", title: "ES 300", auto_make_id: 37},
  {code: "ES300H", title: "ES 300h", auto_make_id: 37},
  {code: "ES330", title: "ES 330", auto_make_id: 37},
  {code: "ES350", title: "ES 350", auto_make_id: 37},
  {code: "GS_MODELS", title: "GS ", auto_make_id: 37},
  {code: "GS300", title: "GS 300", auto_make_id: 37},
  {code: "GS350", title: "GS 350", auto_make_id: 37},
  {code: "GS400", title: "GS 400", auto_make_id: 37},
  {code: "GS430", title: "GS 430", auto_make_id: 37},
  {code: "GS450H", title: "GS 450h", auto_make_id: 37},
  {code: "GS460", title: "GS 460", auto_make_id: 37},
  {code: "GX_MODELS", title: "GX ", auto_make_id: 37},
  {code: "GX460", title: "GX 460", auto_make_id: 37},
  {code: "GX470", title: "GX 470", auto_make_id: 37},
  {code: "HS_MODELS", title: "HS ", auto_make_id: 37},
  {code: "HS250H", title: "HS 250h", auto_make_id: 37},
  {code: "IS_MODELS", title: "IS ", auto_make_id: 37},
  {code: "IS250", title: "IS 250", auto_make_id: 37},
  {code: "IS250C", title: "IS 250C", auto_make_id: 37},
  {code: "IS300", title: "IS 300", auto_make_id: 37},
  {code: "IS350", title: "IS 350", auto_make_id: 37},
  {code: "IS350C", title: "IS 350C", auto_make_id: 37},
  {code: "ISF", title: "IS F", auto_make_id: 37},
  {code: "LEXLFA", title: "LFA", auto_make_id: 37},
  {code: "LS_MODELS", title: "LS ", auto_make_id: 37},
  {code: "LS400", title: "LS 400", auto_make_id: 37},
  {code: "LS430", title: "LS 430", auto_make_id: 37},
  {code: "LS460", title: "LS 460", auto_make_id: 37},
  {code: "LS600H", title: "LS 600h", auto_make_id: 37},
  {code: "LX_MODELS", title: "LX ", auto_make_id: 37},
  {code: "LX450", title: "LX 450", auto_make_id: 37},
  {code: "LX470", title: "LX 470", auto_make_id: 37},
  {code: "LX570", title: "LX 570", auto_make_id: 37},
  {code: "RX_MODELS", title: "RX ", auto_make_id: 37},
  {code: "RX300", title: "RX 300", auto_make_id: 37},
  {code: "RX330", title: "RX 330", auto_make_id: 37},
  {code: "RX350", title: "RX 350", auto_make_id: 37},
  {code: "RX400H", title: "RX 400h", auto_make_id: 37},
  {code: "RX450H", title: "RX 450h", auto_make_id: 37},
  {code: "SC_MODELS", title: "SC ", auto_make_id: 37},
  {code: "SC300", title: "SC 300", auto_make_id: 37},
  {code: "SC400", title: "SC 400", auto_make_id: 37},
  {code: "SC430", title: "SC 430", auto_make_id: 37},
  {code: "LEXOTH", title: "Lexus", auto_make_id: 37},
  {code: "AVIATOR", title: "Aviator", auto_make_id: 38},
  {code: "BLKWOOD", title: "Blackwood", auto_make_id: 38},
  {code: "CONT", title: "Continental", auto_make_id: 38},
  {code: "LSLINCOLN", title: "LS", auto_make_id: 38},
  {code: "MARKLT", title: "Mark LT", auto_make_id: 38},
  {code: "MARK6", title: "Mark VI", auto_make_id: 38},
  {code: "MARK7", title: "Mark VII", auto_make_id: 38},
  {code: "MARK8", title: "Mark VIII", auto_make_id: 38},
  {code: "MKS", title: "MKS", auto_make_id: 38},
  {code: "MKT", title: "MKT", auto_make_id: 38},
  {code: "MKX", title: "MKX", auto_make_id: 38},
  {code: "MKZ", title: "MKZ", auto_make_id: 38},
  {code: "NAVIGA", title: "Navigator", auto_make_id: 38},
  {code: "NAVIGAL", title: "Navigator L", auto_make_id: 38},
  {code: "LINCTC", title: "Town Car", auto_make_id: 38},
  {code: "ZEPHYR", title: "Zephyr", auto_make_id: 38},
  {code: "LINOTH", title: "Lincoln", auto_make_id: 38},
  {code: "ELAN", title: "Elan", auto_make_id: 39},
  {code: "LOTELISE", title: "Elise", auto_make_id: 39},
  {code: "ESPRIT", title: "Esprit", auto_make_id: 39},
  {code: "EVORA", title: "Evora", auto_make_id: 39},
  {code: "EXIGE", title: "Exige", auto_make_id: 39},
  {code: "UNAVAILLOT", title: "Lotus", auto_make_id: 39},
  {code: "430", title: "430", auto_make_id: 40},
  {code: "BITRBO", title: "Biturbo", auto_make_id: 40},
  {code: "COUPEMAS", title: "Coupe", auto_make_id: 40},
  {code: "GRANSPORT", title: "GranSport", auto_make_id: 40},
  {code: "GRANTURISM", title: "GranTurismo", auto_make_id: 40},
  {code: "QP", title: "Quattroporte", auto_make_id: 40},
  {code: "SPYDER", title: "Spyder", auto_make_id: 40},
  {code: "UNAVAILMAS", title: "Maserati", auto_make_id: 40},
  {code: "57MAYBACH", title: "57", auto_make_id: 41},
  {code: "62MAYBACH", title: "62", auto_make_id: 41},
  {code: "UNAVAILMAY", title: "Maybach", auto_make_id: 41},
  {code: "MAZDA323", title: "323", auto_make_id: 42},
  {code: "MAZDA626", title: "626", auto_make_id: 42},
  {code: "929", title: "929", auto_make_id: 42},
  {code: "B-SERIES", title: "B-Series Pickup", auto_make_id: 42},
  {code: "CX-5", title: "CX-5", auto_make_id: 42},
  {code: "CX-7", title: "CX-7", auto_make_id: 42},
  {code: "CX-9", title: "CX-9", auto_make_id: 42},
  {code: "GLC", title: "GLC", auto_make_id: 42},
  {code: "MAZDA2", title: "MAZDA2", auto_make_id: 42},
  {code: "MAZDA3", title: "MAZDA3", auto_make_id: 42},
  {code: "MAZDA5", title: "MAZDA5", auto_make_id: 42},
  {code: "MAZDA6", title: "MAZDA6", auto_make_id: 42},
  {code: "MAZDASPD3", title: "MAZDASPEED3", auto_make_id: 42},
  {code: "MAZDASPD6", title: "MAZDASPEED6", auto_make_id: 42},
  {code: "MIATA", title: "Miata MX5", auto_make_id: 42},
  {code: "MILL", title: "Millenia", auto_make_id: 42},
  {code: "MPV", title: "MPV", auto_make_id: 42},
  {code: "MX3", title: "MX3", auto_make_id: 42},
  {code: "MX6", title: "MX6", auto_make_id: 42},
  {code: "NAVAJO", title: "Navajo", auto_make_id: 42},
  {code: "PROTE", title: "Protege", auto_make_id: 42},
  {code: "PROTE5", title: "Protege5", auto_make_id: 42},
  {code: "RX7", title: "RX-7", auto_make_id: 42},
  {code: "RX8", title: "RX-8", auto_make_id: 42},
  {code: "TRIBUTE", title: "Tribute", auto_make_id: 42},
  {code: "MAZOTH", title: "Mazda", auto_make_id: 42},
  {code: "MP4", title: "MP4-12C", auto_make_id: 43},
  {code: "190_CLASS", title: "190 Class ", auto_make_id: 44},
  {code: "190D", title: "190D", auto_make_id: 44},
  {code: "190E", title: "190E", auto_make_id: 44},
  {code: "240_CLASS", title: "240 Class ", auto_make_id: 44},
  {code: "240D", title: "240D", auto_make_id: 44},
  {code: "300_CLASS_E_CLASS", title: "300 Class / E Class ", auto_make_id: 44},
  {code: "300CD", title: "300CD", auto_make_id: 44},
  {code: "300CE", title: "300CE", auto_make_id: 44},
  {code: "300D", title: "300D", auto_make_id: 44},
  {code: "300E", title: "300E", auto_make_id: 44},
  {code: "300TD", title: "300TD", auto_make_id: 44},
  {code: "300TE", title: "300TE", auto_make_id: 44},
  {code: "C_CLASS", title: "C Class ", auto_make_id: 44},
  {code: "C220", title: "C220", auto_make_id: 44},
  {code: "C230", title: "C230", auto_make_id: 44},
  {code: "C240", title: "C240", auto_make_id: 44},
  {code: "C250", title: "C250", auto_make_id: 44},
  {code: "C280", title: "C280", auto_make_id: 44},
  {code: "C300", title: "C300", auto_make_id: 44},
  {code: "C320", title: "C320", auto_make_id: 44},
  {code: "C32AMG", title: "C32 AMG", auto_make_id: 44},
  {code: "C350", title: "C350", auto_make_id: 44},
  {code: "C36AMG", title: "C36 AMG", auto_make_id: 44},
  {code: "C43AMG", title: "C43 AMG", auto_make_id: 44},
  {code: "C55AMG", title: "C55 AMG", auto_make_id: 44},
  {code: "C63AMG", title: "C63 AMG", auto_make_id: 44},
  {code: "CL_CLASS", title: "CL Class ", auto_make_id: 44},
  {code: "CL500", title: "CL500", auto_make_id: 44},
  {code: "CL550", title: "CL550", auto_make_id: 44},
  {code: "CL55AMG", title: "CL55 AMG", auto_make_id: 44},
  {code: "CL600", title: "CL600", auto_make_id: 44},
  {code: "CL63AMG", title: "CL63 AMG", auto_make_id: 44},
  {code: "CL65AMG", title: "CL65 AMG", auto_make_id: 44},
  {code: "CLK_CLASS", title: "CLK Class ", auto_make_id: 44},
  {code: "CLK320", title: "CLK320", auto_make_id: 44},
  {code: "CLK350", title: "CLK350", auto_make_id: 44},
  {code: "CLK430", title: "CLK430", auto_make_id: 44},
  {code: "CLK500", title: "CLK500", auto_make_id: 44},
  {code: "CLK550", title: "CLK550", auto_make_id: 44},
  {code: "CLK55AMG", title: "CLK55 AMG", auto_make_id: 44},
  {code: "CLK63AMG", title: "CLK63 AMG", auto_make_id: 44},
  {code: "CLS_CLASS", title: "CLS Class ", auto_make_id: 44},
  {code: "CLS500", title: "CLS500", auto_make_id: 44},
  {code: "CLS550", title: "CLS550", auto_make_id: 44},
  {code: "CLS55AMG", title: "CLS55 AMG", auto_make_id: 44},
  {code: "CLS63AMG", title: "CLS63 AMG", auto_make_id: 44},
  {code: "E_CLASS", title: "E Class ", auto_make_id: 44},
  {code: "260E", title: "260E", auto_make_id: 44},
  {code: "280CE", title: "280CE", auto_make_id: 44},
  {code: "280E", title: "280E", auto_make_id: 44},
  {code: "400E", title: "400E", auto_make_id: 44},
  {code: "500E", title: "500E", auto_make_id: 44},
  {code: "E300", title: "E300", auto_make_id: 44},
  {code: "E320", title: "E320", auto_make_id: 44},
  {code: "E320BLUE", title: "E320 Bluetec", auto_make_id: 44},
  {code: "E320CDI", title: "E320 CDI", auto_make_id: 44},
  {code: "E350", title: "E350", auto_make_id: 44},
  {code: "E350BLUE", title: "E350 Bluetec", auto_make_id: 44},
  {code: "E400", title: "E400 Hybr:id", auto_make_id: 44},
  {code: "E420", title: "E420", auto_make_id: 44},
  {code: "E430", title: "E430", auto_make_id: 44},
  {code: "E500", title: "E500", auto_make_id: 44},
  {code: "E550", title: "E550", auto_make_id: 44},
  {code: "E55AMG", title: "E55 AMG", auto_make_id: 44},
  {code: "E63AMG", title: "E63 AMG", auto_make_id: 44},
  {code: "G_CLASS", title: "G Class ", auto_make_id: 44},
  {code: "G500", title: "G500", auto_make_id: 44},
  {code: "G550", title: "G550", auto_make_id: 44},
  {code: "G55AMG", title: "G55 AMG", auto_make_id: 44},
  {code: "G63AMG", title: "G63 AMG", auto_make_id: 44},
  {code: "GL_CLASS", title: "GL Class ", auto_make_id: 44},
  {code: "GL320BLUE", title: "GL320 Bluetec", auto_make_id: 44},
  {code: "GL320CDI", title: "GL320 CDI", auto_make_id: 44},
  {code: "GL350BLUE", title: "GL350 Bluetec", auto_make_id: 44},
  {code: "GL450", title: "GL450", auto_make_id: 44},
  {code: "GL550", title: "GL550", auto_make_id: 44},
  {code: "GLK_CLASS", title: "GLK Class ", auto_make_id: 44},
  {code: "GLK350", title: "GLK350", auto_make_id: 44},
  {code: "M_CLASS", title: "M Class ", auto_make_id: 44},
  {code: "ML320", title: "ML320", auto_make_id: 44},
  {code: "ML320BLUE", title: "ML320 Bluetec", auto_make_id: 44},
  {code: "ML320CDI", title: "ML320 CDI", auto_make_id: 44},
  {code: "ML350", title: "ML350", auto_make_id: 44},
  {code: "ML350BLUE", title: "ML350 Bluetec", auto_make_id: 44},
  {code: "ML430", title: "ML430", auto_make_id: 44},
  {code: "ML450HY", title: "ML450 Hybr:id", auto_make_id: 44},
  {code: "ML500", title: "ML500", auto_make_id: 44},
  {code: "ML550", title: "ML550", auto_make_id: 44},
  {code: "ML55AMG", title: "ML55 AMG", auto_make_id: 44},
  {code: "ML63AMG", title: "ML63 AMG", auto_make_id: 44},
  {code: "R_CLASS", title: "R Class ", auto_make_id: 44},
  {code: "R320BLUE", title: "R320 Bluetec", auto_make_id: 44},
  {code: "R320CDI", title: "R320 CDI", auto_make_id: 44},
  {code: "R350", title: "R350", auto_make_id: 44},
  {code: "R350BLUE", title: "R350 Bluetec", auto_make_id: 44},
  {code: "R500", title: "R500", auto_make_id: 44},
  {code: "R63AMG", title: "R63 AMG", auto_make_id: 44},
  {code: "S_CLASS", title: "S Class ", auto_make_id: 44},
  {code: "300SD", title: "300SD", auto_make_id: 44},
  {code: "300SDL", title: "300SDL", auto_make_id: 44},
  {code: "300SE", title: "300SE", auto_make_id: 44},
  {code: "300SEL", title: "300SEL", auto_make_id: 44},
  {code: "350SD", title: "350SD", auto_make_id: 44},
  {code: "350SDL", title: "350SDL", auto_make_id: 44},
  {code: "380SE", title: "380SE", auto_make_id: 44},
  {code: "380SEC", title: "380SEC", auto_make_id: 44},
  {code: "380SEL", title: "380SEL", auto_make_id: 44},
  {code: "400SE", title: "400SE", auto_make_id: 44},
  {code: "400SEL", title: "400SEL", auto_make_id: 44},
  {code: "420SEL", title: "420SEL", auto_make_id: 44},
  {code: "500SEC", title: "500SEC", auto_make_id: 44},
  {code: "500SEL", title: "500SEL", auto_make_id: 44},
  {code: "560SEC", title: "560SEC", auto_make_id: 44},
  {code: "560SEL", title: "560SEL", auto_make_id: 44},
  {code: "600SEC", title: "600SEC", auto_make_id: 44},
  {code: "600SEL", title: "600SEL", auto_make_id: 44},
  {code: "S320", title: "S320", auto_make_id: 44},
  {code: "S350", title: "S350", auto_make_id: 44},
  {code: "S350BLUE", title: "S350 Bluetec", auto_make_id: 44},
  {code: "S400HY", title: "S400 Hybr:id", auto_make_id: 44},
  {code: "S420", title: "S420", auto_make_id: 44},
  {code: "S430", title: "S430", auto_make_id: 44},
  {code: "S500", title: "S500", auto_make_id: 44},
  {code: "S550", title: "S550", auto_make_id: 44},
  {code: "S55AMG", title: "S55 AMG", auto_make_id: 44},
  {code: "S600", title: "S600", auto_make_id: 44},
  {code: "S63AMG", title: "S63 AMG", auto_make_id: 44},
  {code: "S65AMG", title: "S65 AMG", auto_make_id: 44},
  {code: "SL_CLASS", title: "SL Class ", auto_make_id: 44},
  {code: "300SL", title: "300SL", auto_make_id: 44},
  {code: "380SL", title: "380SL", auto_make_id: 44},
  {code: "380SLC", title: "380SLC", auto_make_id: 44},
  {code: "500SL", title: "500SL", auto_make_id: 44},
  {code: "560SL", title: "560SL", auto_make_id: 44},
  {code: "600SL", title: "600SL", auto_make_id: 44},
  {code: "SL320", title: "SL320", auto_make_id: 44},
  {code: "SL500", title: "SL500", auto_make_id: 44},
  {code: "SL550", title: "SL550", auto_make_id: 44},
  {code: "SL55AMG", title: "SL55 AMG", auto_make_id: 44},
  {code: "SL600", title: "SL600", auto_make_id: 44},
  {code: "SL63AMG", title: "SL63 AMG", auto_make_id: 44},
  {code: "SL65AMG", title: "SL65 AMG", auto_make_id: 44},
  {code: "SLK_CLASS", title: "SLK Class ", auto_make_id: 44},
  {code: "SLK230", title: "SLK230", auto_make_id: 44},
  {code: "SLK250", title: "SLK250", auto_make_id: 44},
  {code: "SLK280", title: "SLK280", auto_make_id: 44},
  {code: "SLK300", title: "SLK300", auto_make_id: 44},
  {code: "SLK320", title: "SLK320", auto_make_id: 44},
  {code: "SLK32AMG", title: "SLK32 AMG", auto_make_id: 44},
  {code: "SLK350", title: "SLK350", auto_make_id: 44},
  {code: "SLK55AMG", title: "SLK55 AMG", auto_make_id: 44},
  {code: "SLR_CLASS", title: "SLR Class ", auto_make_id: 44},
  {code: "SLR", title: "SLR", auto_make_id: 44},
  {code: "SLS_CLASS", title: "SLS Class ", auto_make_id: 44},
  {code: "SLSAMG", title: "SLS AMG", auto_make_id: 44},
  {code: "SPRINTER_CLASS", title: "Sprinter Class ", auto_make_id: 44},
  {code: "MBSPRINTER", title: "Sprinter", auto_make_id: 44},
  {code: "MBOTH", title: "Mercedes-Benz", auto_make_id: 44},
  {code: "CAPRI", title: "Capri", auto_make_id: 45},
  {code: "COUGAR", title: "Cougar", auto_make_id: 45},
  {code: "MERCGRAND", title: "Grand Marquis", auto_make_id: 45},
  {code: "LYNX", title: "Lynx", auto_make_id: 45},
  {code: "MARAUDER", title: "Marauder", auto_make_id: 45},
  {code: "MARINER", title: "Mariner", auto_make_id: 45},
  {code: "MARQ", title: "Marquis", auto_make_id: 45},
  {code: "MILAN", title: "Milan", auto_make_id: 45},
  {code: "MONTEGO", title: "Montego", auto_make_id: 45},
  {code: "MONTEREY", title: "Monterey", auto_make_id: 45},
  {code: "MOUNTA", title: "Mountaineer", auto_make_id: 45},
  {code: "MYSTIQ", title: "Mystique", auto_make_id: 45},
  {code: "SABLE", title: "Sable", auto_make_id: 45},
  {code: "TOPAZ", title: "Topaz", auto_make_id: 45},
  {code: "TRACER", title: "Tracer", auto_make_id: 45},
  {code: "VILLA", title: "Villager", auto_make_id: 45},
  {code: "MERCZEP", title: "Zephyr", auto_make_id: 45},
  {code: "MEOTH", title: "Mercury", auto_make_id: 45},
  {code: "SCORP", title: "Scorpio", auto_make_id: 46},
  {code: "XR4TI", title: "XR4Ti", auto_make_id: 46},
  {code: "MEROTH", title: "Merkur", auto_make_id: 46},
  {code: "COOPRCLUB_MODELS", title: "Cooper Clubman ", auto_make_id: 47},
  {code: "COOPERCLUB", title: "Cooper Clubman", auto_make_id: 47},
  {code: "COOPRCLUBS", title: "Cooper S Clubman", auto_make_id: 47},
  {code: "COOPCOUNTRY_MODELS", title: "Cooper Countryman ", auto_make_id: 47},
  {code: "COUNTRYMAN", title: "Cooper Countryman", auto_make_id: 47},
  {code: "COUNTRYMNS", title: "Cooper S Countryman", auto_make_id: 47},
  {code: "COOPCOUP_MODELS", title: "Cooper Coupe ", auto_make_id: 47},
  {code: "MINICOUPE", title: "Cooper Coupe", auto_make_id: 47},
  {code: "MINISCOUPE", title: "Cooper S Coupe", auto_make_id: 47},
  {code: "COOPER_MODELS", title: "Cooper ", auto_make_id: 47},
  {code: "COOPER", title: "Cooper", auto_make_id: 47},
  {code: "COOPERS", title: "Cooper S", auto_make_id: 47},
  {code: "COOPRROAD_MODELS", title: "Cooper Roadster ", auto_make_id: 47},
  {code: "COOPERROAD", title: "Cooper Roadster", auto_make_id: 47},
  {code: "COOPERSRD", title: "Cooper S Roadster", auto_make_id: 47},
  {code: "3000GT", title: "3000GT", auto_make_id: 48},
  {code: "CORD", title: "Cordia", auto_make_id: 48},
  {code: "DIAMAN", title: "Diamante", auto_make_id: 48},
  {code: "ECLIP", title: "Eclipse", auto_make_id: 48},
  {code: "ENDEAVOR", title: "Endeavor", auto_make_id: 48},
  {code: "MITEXP", title: "Expo", auto_make_id: 48},
  {code: "GALANT", title: "Galant", auto_make_id: 48},
  {code: "MITI", title: "i", auto_make_id: 48},
  {code: "LANCERMITS", title: "Lancer", auto_make_id: 48},
  {code: "LANCEREVO", title: "Lancer Evolution", auto_make_id: 48},
  {code: "MITPU", title: "Mighty Max", auto_make_id: 48},
  {code: "MIRAGE", title: "Mirage", auto_make_id: 48},
  {code: "MONT", title: "Montero", auto_make_id: 48},
  {code: "MONTSPORT", title: "Montero Sport", auto_make_id: 48},
  {code: "OUTLANDER", title: "Outlander", auto_make_id: 48},
  {code: "OUTLANDSPT", title: "Outlander Sport", auto_make_id: 48},
  {code: "PRECIS", title: "Precis", auto_make_id: 48},
  {code: "RA:idERMITS", title: "Ra:ider", auto_make_id: 48},
  {code: "SIGMA", title: "Sigma", auto_make_id: 48},
  {code: "MITSTAR", title: "Starion", auto_make_id: 48},
  {code: "TRED", title: "Tredia", auto_make_id: 48},
  {code: "MITVAN", title: "Van", auto_make_id: 48},
  {code: "MITOTH", title: "Mitsubishi", auto_make_id: 48},
  {code: "NIS200SX", title: "200SX", auto_make_id: 49},
  {code: "240SX", title: "240SX", auto_make_id: 49},
  {code: "300ZXTURBO", title: "300ZX", auto_make_id: 49},
  {code: "350Z", title: "350Z", auto_make_id: 49},
  {code: "370Z", title: "370Z", auto_make_id: 49},
  {code: "ALTIMA", title: "Altima", auto_make_id: 49},
  {code: "PATHARMADA", title: "Armada", auto_make_id: 49},
  {code: "AXXESS", title: "Axxess", auto_make_id: 49},
  {code: "CUBE", title: "Cube", auto_make_id: 49},
  {code: "FRONTI", title: "Frontier", auto_make_id: 49},
  {code: "GT-R", title: "GT-R", auto_make_id: 49},
  {code: "JUKE", title: "Juke", auto_make_id: 49},
  {code: "LEAF", title: "Leaf", auto_make_id: 49},
  {code: "MAX", title: "Maxima", auto_make_id: 49},
  {code: "MURANO", title: "Murano", auto_make_id: 49},
  {code: "MURANOCROS", title: "Murano CrossCabriolet", auto_make_id: 49},
  {code: "NV", title: "NV", auto_make_id: 49},
  {code: "NX", title: "NX", auto_make_id: 49},
  {code: "PATH", title: "Pathfinder", auto_make_id: 49},
  {code: "NISPU", title: "Pickup", auto_make_id: 49},
  {code: "PULSAR", title: "Pulsar", auto_make_id: 49},
  {code: "QUEST", title: "Quest", auto_make_id: 49},
  {code: "ROGUE", title: "Rogue", auto_make_id: 49},
  {code: "SENTRA", title: "Sentra", auto_make_id: 49},
  {code: "STANZA", title: "Stanza", auto_make_id: 49},
  {code: "TITAN", title: "Titan", auto_make_id: 49},
  {code: "NISVAN", title: "Van", auto_make_id: 49},
  {code: "VERSA", title: "Versa", auto_make_id: 49},
  {code: "XTERRA", title: "Xterra", auto_make_id: 49},
  {code: "NISSOTH", title: "Nissan", auto_make_id: 49},
  {code: "88", title: "88", auto_make_id: 50},
  {code: "ACHIEV", title: "Achieva", auto_make_id: 50},
  {code: "ALERO", title: "Alero", auto_make_id: 50},
  {code: "AURORA", title: "Aurora", auto_make_id: 50},
  {code: "BRAV", title: "Bravada", auto_make_id: 50},
  {code: "CUCR", title: "Custom Cruiser", auto_make_id: 50},
  {code: "OLDCUS", title: "Cutlass", auto_make_id: 50},
  {code: "OLDCALAIS", title: "Cutlass Calais", auto_make_id: 50},
  {code: "CIERA", title: "Cutlass Ciera", auto_make_id: 50},
  {code: "CSUPR", title: "Cutlass Supreme", auto_make_id: 50},
  {code: "OLDSFIR", title: "Firenza", auto_make_id: 50},
  {code: "INTRIG", title: "Intrigue", auto_make_id: 50},
  {code: "98", title: "Ninety-Eight", auto_make_id: 50},
  {code: "OMEG", title: "Omega", auto_make_id: 50},
  {code: "REGEN", title: "Regency", auto_make_id: 50},
  {code: "SILHO", title: "Silhouette", auto_make_id: 50},
  {code: "TORO", title: "Toronado", auto_make_id: 50},
  {code: "OLDOTH", title: "Oldsmobile", auto_make_id: 50},
  {code: "405", title: "405", auto_make_id: 51},
  {code: "504", title: "504", auto_make_id: 51},
  {code: "505", title: "505", auto_make_id: 51},
  {code: "604", title: "604", auto_make_id: 51},
  {code: "UNAVAILPEU", title: "Peugeot", auto_make_id: 51},
  {code: "ACC", title: "Acclaim", auto_make_id: 52},
  {code: "ARROW", title: "Arrow", auto_make_id: 52},
  {code: "BREEZE", title: "Breeze", auto_make_id: 52},
  {code: "CARAVE", title: "Caravelle", auto_make_id: 52},
  {code: "CHAMP", title: "Champ", auto_make_id: 52},
  {code: "COLT", title: "Colt", auto_make_id: 52},
  {code: "PLYMCONQ", title: "Conquest", auto_make_id: 52},
  {code: "GRANFURY", title: "Gran Fury", auto_make_id: 52},
  {code: "PLYMGRANV", title: "Grand Voyager", auto_make_id: 52},
  {code: "HORI", title: "Horizon", auto_make_id: 52},
  {code: "LASER", title: "Laser", auto_make_id: 52},
  {code: "NEON", title: "Neon", auto_make_id: 52},
  {code: "PROWLE", title: "Prowler", auto_make_id: 52},
  {code: "RELI", title: "Reliant", auto_make_id: 52},
  {code: "SAPPOROPLY", title: "Sapporo", auto_make_id: 52},
  {code: "SCAMP", title: "Scamp", auto_make_id: 52},
  {code: "SUNDAN", title: "Sundance", auto_make_id: 52},
  {code: "TRAILDUST", title: "Trailduster", auto_make_id: 52},
  {code: "VOYA", title: "Voyager", auto_make_id: 52},
  {code: "PLYOTH", title: "Plymouth", auto_make_id: 52},
  {code: "T-1000", title: "1000", auto_make_id: 53},
  {code: "6000", title: "6000", auto_make_id: 53},
  {code: "AZTEK", title: "Aztek", auto_make_id: 53},
  {code: "BON", title: "Bonneville", auto_make_id: 53},
  {code: "CATALINA", title: "Catalina", auto_make_id: 53},
  {code: "FIERO", title: "Fiero", auto_make_id: 53},
  {code: "FBIRD", title: "Firebird", auto_make_id: 53},
  {code: "G3", title: "G3", auto_make_id: 53},
  {code: "G5", title: "G5", auto_make_id: 53},
  {code: "G6", title: "G6", auto_make_id: 53},
  {code: "G8", title: "G8", auto_make_id: 53},
  {code: "GRNDAM", title: "Grand Am", auto_make_id: 53},
  {code: "GP", title: "Grand Prix", auto_make_id: 53},
  {code: "GTO", title: "GTO", auto_make_id: 53},
  {code: "J2000", title: "J2000", auto_make_id: 53},
  {code: "LEMANS", title: "Le Mans", auto_make_id: 53},
  {code: "MONTANA", title: "Montana", auto_make_id: 53},
  {code: "PARISI", title: "Parisienne", auto_make_id: 53},
  {code: "PHOENIX", title: "Phoenix", auto_make_id: 53},
  {code: "SAFARIPONT", title: "Safari", auto_make_id: 53},
  {code: "SOLSTICE", title: "Solstice", auto_make_id: 53},
  {code: "SUNBIR", title: "Sunbird", auto_make_id: 53},
  {code: "SUNFIR", title: "Sunfire", auto_make_id: 53},
  {code: "TORRENT", title: "Torrent", auto_make_id: 53},
  {code: "TS", title: "Trans Sport", auto_make_id: 53},
  {code: "VIBE", title: "Vibe", auto_make_id: 53},
  {code: "PONOTH", title: "Pontiac", auto_make_id: 53},
  {code: "911", title: "911", auto_make_id: 54},
  {code: "924", title: "924", auto_make_id: 54},
  {code: "928", title: "928", auto_make_id: 54},
  {code: "944", title: "944", auto_make_id: 54},
  {code: "968", title: "968", auto_make_id: 54},
  {code: "BOXSTE", title: "Boxster", auto_make_id: 54},
  {code: "CARRERAGT", title: "Carrera GT", auto_make_id: 54},
  {code: "CAYENNE", title: "Cayenne", auto_make_id: 54},
  {code: "CAYMAN", title: "Cayman", auto_make_id: 54},
  {code: "PANAMERA", title: "Panamera", auto_make_id: 54},
  {code: "POROTH", title: "Porsche", auto_make_id: 54},
  {code: "RAM1504WD", title: "1500", auto_make_id: 55},
  {code: "RAM25002WD", title: "2500", auto_make_id: 55},
  {code: "RAM3502WD", title: "3500", auto_make_id: 55},
  {code: "RAM4500", title: "4500", auto_make_id: 55},
  {code: "18I", title: "18i", auto_make_id: 56},
  {code: "FU", title: "Fuego", auto_make_id: 56},
  {code: "LECAR", title: "Le Car", auto_make_id: 56},
  {code: "R18", title: "R18", auto_make_id: 56},
  {code: "RENSPORT", title: "Sportwagon", auto_make_id: 56},
  {code: "UNAVAILREN", title: "Renault", auto_make_id: 56},
  {code: "CAMAR", title: "Camargue", auto_make_id: 57},
  {code: "CORN", title: "Corniche", auto_make_id: 57},
  {code: "GHOST", title: "Ghost", auto_make_id: 57},
  {code: "PARKWARD", title: "Park Ward", auto_make_id: 57},
  {code: "PHANT", title: "Phantom", auto_make_id: 57},
  {code: "DAWN", title: "Silver Dawn", auto_make_id: 57},
  {code: "SILSERAPH", title: "Silver Seraph", auto_make_id: 57},
  {code: "RRSPIR", title: "Silver Spirit", auto_make_id: 57},
  {code: "SPUR", title: "Silver Spur", auto_make_id: 57},
  {code: "UNAVAILRR", title: "Rolls-Royce", auto_make_id: 57},
  {code: "9-2X", title: "9-2X", auto_make_id: 58},
  {code: "9-3", title: "9-3", auto_make_id: 58},
  {code: "9-4X", title: "9-4X", auto_make_id: 58},
  {code: "9-5", title: "9-5", auto_make_id: 58},
  {code: "97X", title: "9-7X", auto_make_id: 58},
  {code: "900", title: "900", auto_make_id: 58},
  {code: "9000", title: "9000", auto_make_id: 58},
  {code: "SAOTH", title: "Saab", auto_make_id: 58},
  {code: "ASTRA", title: "Astra", auto_make_id: 59},
  {code: "AURA", title: "Aura", auto_make_id: 59},
  {code: "ION", title: "ION", auto_make_id: 59},
  {code: "L_SERIES", title: "L Series ", auto_make_id: 59},
  {code: "L100", title: "L100", auto_make_id: 59},
  {code: "L200", title: "L200", auto_make_id: 59},
  {code: "L300", title: "L300", auto_make_id: 59},
  {code: "LSSATURN", title: "LS", auto_make_id: 59},
  {code: "LW_SERIES", title: "LW Series ", auto_make_id: 59},
  {code: "LW", title: "LW1", auto_make_id: 59},
  {code: "LW2", title: "LW2", auto_make_id: 59},
  {code: "LW200", title: "LW200", auto_make_id: 59},
  {code: "LW300", title: "LW300", auto_make_id: 59},
  {code: "OUTLOOK", title: "Outlook", auto_make_id: 59},
  {code: "RELAY", title: "Relay", auto_make_id: 59},
  {code: "SC_SERIES", title: "SC Series ", auto_make_id: 59},
  {code: "SC1", title: "SC1", auto_make_id: 59},
  {code: "SC2", title: "SC2", auto_make_id: 59},
  {code: "SKY", title: "Sky", auto_make_id: 59},
  {code: "SL_SERIES", title: "SL Series ", auto_make_id: 59},
  {code: "SL", title: "SL", auto_make_id: 59},
  {code: "SL1", title: "SL1", auto_make_id: 59},
  {code: "SL2", title: "SL2", auto_make_id: 59},
  {code: "SW_SERIES", title: "SW Series ", auto_make_id: 59},
  {code: "SW1", title: "SW1", auto_make_id: 59},
  {code: "SW2", title: "SW2", auto_make_id: 59},
  {code: "VUE", title: "Vue", auto_make_id: 59},
  {code: "SATOTH", title: "Saturn", auto_make_id: 59},
  {code: "SCIFRS", title: "FR-S", auto_make_id: 60},
  {code: "IQ", title: "iQ", auto_make_id: 60},
  {code: "TC", title: "tC", auto_make_id: 60},
  {code: "XA", title: "xA", auto_make_id: 60},
  {code: "XB", title: "xB", auto_make_id: 60},
  {code: "XD", title: "xD", auto_make_id: 60},
  {code: "FORTWO", title: "fortwo", auto_make_id: 61},
  {code: "SMOTH", title: "smart", auto_make_id: 61},
  {code: "SRTVIPER", title: "Viper", auto_make_id: 62},
  {code: "825", title: "825", auto_make_id: 63},
  {code: "827", title: "827", auto_make_id: 63},
  {code: "UNAVAILSTE", title: "Sterling", auto_make_id: 63},
  {code: "BAJA", title: "Baja", auto_make_id: 64},
  {code: "BRAT", title: "Brat", auto_make_id: 64},
  {code: "SUBBRZ", title: "BRZ", auto_make_id: 64},
  {code: "FOREST", title: "Forester", auto_make_id: 64},
  {code: "IMPREZ", title: "Impreza", auto_make_id: 64},
  {code: "IMPWRX", title: "Impreza WRX", auto_make_id: 64},
  {code: "JUSTY", title: "Justy", auto_make_id: 64},
  {code: "SUBL", title: "L Series", auto_make_id: 64},
  {code: "LEGACY", title: "Legacy", auto_make_id: 64},
  {code: "LOYALE", title: "Loyale", auto_make_id: 64},
  {code: "SUBOUTBK", title: "Outback", auto_make_id: 64},
  {code: "SVX", title: "SVX", auto_make_id: 64},
  {code: "B9TRIBECA", title: "Tribeca", auto_make_id: 64},
  {code: "XT", title: "XT", auto_make_id: 64},
  {code: "XVCRSSTREK", title: "XV Crosstrek", auto_make_id: 64},
  {code: "SUBOTH", title: "Subaru", auto_make_id: 64},
  {code: "AERIO", title: "Aerio", auto_make_id: 65},
  {code: "EQUATOR", title: "Equator", auto_make_id: 65},
  {code: "ESTEEM", title: "Esteem", auto_make_id: 65},
  {code: "FORENZA", title: "Forenza", auto_make_id: 65},
  {code: "GRANDV", title: "Grand Vitara", auto_make_id: 65},
  {code: "KIZASHI", title: "Kizashi", auto_make_id: 65},
  {code: "RENO", title: "Reno", auto_make_id: 65},
  {code: "SAMUR", title: "Samurai", auto_make_id: 65},
  {code: "S:idE", title: "S:idekick", auto_make_id: 65},
  {code: "SWIFT", title: "Swift", auto_make_id: 65},
  {code: "SX4", title: "SX4", auto_make_id: 65},
  {code: "VERONA", title: "Verona", auto_make_id: 65},
  {code: "VITARA", title: "Vitara", auto_make_id: 65},
  {code: "X90", title: "X-90", auto_make_id: 65},
  {code: "XL7", title: "XL7", auto_make_id: 65},
  {code: "SUZOTH", title: "Suzuki", auto_make_id: 65},
  {code: "ROADSTER", title: "Roadster", auto_make_id: 66},
  {code: "4RUN", title: "4Runner", auto_make_id: 67},
  {code: "AVALON", title: "Avalon", auto_make_id: 67},
  {code: "CAMRY", title: "Camry", auto_make_id: 67},
  {code: "CELICA", title: "Celica", auto_make_id: 67},
  {code: "COROL", title: "Corolla", auto_make_id: 67},
  {code: "CORONA", title: "Corona", auto_make_id: 67},
  {code: "CRESS", title: "Cress:ida", auto_make_id: 67},
  {code: "ECHO", title: "Echo", auto_make_id: 67},
  {code: "FJCRUIS", title: "FJ Cruiser", auto_make_id: 67},
  {code: "HIGHLANDER", title: "Highlander", auto_make_id: 67},
  {code: "LC", title: "Land Cruiser", auto_make_id: 67},
  {code: "MATRIX", title: "Matrix", auto_make_id: 67},
  {code: "MR2", title: "MR2", auto_make_id: 67},
  {code: "MR2SPYDR", title: "MR2 Spyder", auto_make_id: 67},
  {code: "PASEO", title: "Paseo", auto_make_id: 67},
  {code: "PICKUP", title: "Pickup", auto_make_id: 67},
  {code: "PREVIA", title: "Previa", auto_make_id: 67},
  {code: "PRIUS", title: "Prius", auto_make_id: 67},
  {code: "PRIUSC", title: "Prius C", auto_make_id: 67},
  {code: "PRIUSV", title: "Prius V", auto_make_id: 67},
  {code: "RAV4", title: "RAV4", auto_make_id: 67},
  {code: "SEQUOIA", title: "Sequoia", auto_make_id: 67},
  {code: "SIENNA", title: "Sienna", auto_make_id: 67},
  {code: "SOLARA", title: "Solara", auto_make_id: 67},
  {code: "STARLET", title: "Starlet", auto_make_id: 67},
  {code: "SUPRA", title: "Supra", auto_make_id: 67},
  {code: "T100", title: "T100", auto_make_id: 67},
  {code: "TACOMA", title: "Tacoma", auto_make_id: 67},
  {code: "TERCEL", title: "Tercel", auto_make_id: 67},
  {code: "TUNDRA", title: "Tundra", auto_make_id: 67},
  {code: "TOYVAN", title: "Van", auto_make_id: 67},
  {code: "VENZA", title: "Venza", auto_make_id: 67},
  {code: "YARIS", title: "Yaris", auto_make_id: 67},
  {code: "TOYOTH", title: "Toyota", auto_make_id: 67},
  {code: "TR7", title: "TR7", auto_make_id: 68},
  {code: "TR8", title: "TR8", auto_make_id: 68},
  {code: "TRIOTH", title: "Triumph", auto_make_id: 68},
  {code: "BEETLE", title: "Beetle", auto_make_id: 69},
  {code: "VOLKSCAB", title: "Cabrio", auto_make_id: 69},
  {code: "CAB", title: "Cabriolet", auto_make_id: 69},
  {code: "CC", title: "CC", auto_make_id: 69},
  {code: "CORR", title: "Corrado", auto_make_id: 69},
  {code: "DASHER", title: "Dasher", auto_make_id: 69},
  {code: "EOS", title: "Eos", auto_make_id: 69},
  {code: "EUROVAN", title: "Eurovan", auto_make_id: 69},
  {code: "VOLKSFOX", title: "Fox", auto_make_id: 69},
  {code: "GLI", title: "GLI", auto_make_id: 69},
  {code: "GOLFR", title: "Golf R", auto_make_id: 69},
  {code: "GTI", title: "GTI", auto_make_id: 69},
  {code: "GOLFANDRABBITMODELS", title: "Golf and Rabbit ", auto_make_id: 69},
  {code: "GOLF", title: "Golf", auto_make_id: 69},
  {code: "RABBIT", title: "Rabbit", auto_make_id: 69},
  {code: "JET", title: "Jetta", auto_make_id: 69},
  {code: "PASS", title: "Passat", auto_make_id: 69},
  {code: "PHAETON", title: "Phaeton", auto_make_id: 69},
  {code: "RABBITPU", title: "Pickup", auto_make_id: 69},
  {code: "QUAN", title: "Quantum", auto_make_id: 69},
  {code: "R32", title: "R32", auto_make_id: 69},
  {code: "ROUTAN", title: "Routan", auto_make_id: 69},
  {code: "SCIR", title: "Scirocco", auto_make_id: 69},
  {code: "TIGUAN", title: "Tiguan", auto_make_id: 69},
  {code: "TOUAREG", title: "Touareg", auto_make_id: 69},
  {code: "VANAG", title: "Vanagon", auto_make_id: 69},
  {code: "VWOTH", title: "Volkswagen", auto_make_id: 69},
  {code: "240", title: "240", auto_make_id: 70},
  {code: "260", title: "260", auto_make_id: 70},
  {code: "740", title: "740", auto_make_id: 70},
  {code: "760", title: "760", auto_make_id: 70},
  {code: "780", title: "780", auto_make_id: 70},
  {code: "850", title: "850", auto_make_id: 70},
  {code: "940", title: "940", auto_make_id: 70},
  {code: "960", title: "960", auto_make_id: 70},
  {code: "C30", title: "C30", auto_make_id: 70},
  {code: "C70", title: "C70", auto_make_id: 70},
  {code: "S40", title: "S40", auto_make_id: 70},
  {code: "S60", title: "S60", auto_make_id: 70},
  {code: "S70", title: "S70", auto_make_id: 70},
  {code: "S80", title: "S80", auto_make_id: 70},
  {code: "S90", title: "S90", auto_make_id: 70},
  {code: "V40", title: "V40", auto_make_id: 70},
  {code: "V50", title: "V50", auto_make_id: 70},
  {code: "V70", title: "V70", auto_make_id: 70},
  {code: "V90", title: "V90", auto_make_id: 70},
  {code: "XC60", title: "XC60", auto_make_id: 70},
  {code: "XC", title: "XC70", auto_make_id: 70},
  {code: "XC90", title: "XC90", auto_make_id: 70},
  {code: "VOLOTH", title: "Volvo", auto_make_id: 70},
  {code: "GV", title: "GV", auto_make_id: 71},
  {code: "GVC", title: "GVC", auto_make_id: 71},
  {code: "GVL", title: "GVL", auto_make_id: 71},
  {code: "GVS", title: "GVS", auto_make_id: 71},
  {code: "GVX", title: "GVX", auto_make_id: 71},
  {code: "YUOTH", title: "Yugo", auto_make_id: 71}
])